feat(Builders): Add partner wallets + industry wallets
skalenetwork/docs.skale.space pull request #117
Opened 2024-07-23 18:00 UTC by manuelbarbas

2024-07-23 20:41 UTC, TheGreatAxios requested changes

2024-07-23 20:41 UTC, TheGreatAxios commented on src/content/docs/builders/tools/wallets/custodial/crossmint.mdx
> +With Crossmint, you can seamlessly integrate web3 capabilities into your website or app. Create wallets for existing users via API and for new users at sign-up. Additionally, you can build quick, plu
Proposal

Crossmint enables you to seamlessly integrate key Web3 functionalty into your application or game.
Create wallets invisibly through their simple APIs for new or existing users. You can use this to quickly enable blockchain without forcing seed phrases and passwords onto users.

2024-07-23 20:41 UTC, TheGreatAxios commented on src/content/docs/builders/tools/wallets/custodial/crossmint.mdx
> +    Please visit developer console, select the [staging](https://staging.crossmint.com/signin?callbackUrl=/console) or [production](https://www.crossmint.com/signin?callbackUrl=/console) environment
Make staging -> staging/testnet
Make production -> production/mainnet

2024-07-23 20:41 UTC, TheGreatAxios commented on src/content/docs/builders/tools/wallets/custodial/crossmint.mdx
Let's make sure it's clear that Crossmint is Nebula only pls

2024-07-23 20:41 UTC, TheGreatAxios commented on src/content/docs/builders/tools/wallets/non-custodial/metakeep.mdx
> +MetaKeep provides full self-custody of assets without the need for a hardware wallet. They achieve this with a secure, decentralized virtual environment. Their reliable and cost-effective innovations
MetaKeep offers API based wallets and functionality through abstracted hardware wallets.
This achieve this through the use of industry standard hardware wallets managed automatically by their service. Their reliable and cost-effective innovations promote mass adoption. Additionally, the team offers insurance polices to enhance user confidence.

2024-07-24 11:34 UTC, manuelbarbas commented on src/content/docs/builders/tools/wallets/custodial/crossmint.mdx
Let me know what you think about this. Not totally sure about it but it was the best idea I got so far
Ideally this or other solution can be used for the rest of the tools. Possible tags could be: SKALE Nebula, Europa, Titan, Calypso and Agnostic  

Also, I'm thinking that ideally I could add this to the <ToolLayout> component

<img width="752" alt="Screenshot 2024-07-24 at 12 29 58" src="https://github.com/user-attachments/assets/63bfc88d-2116-46d0-b342-d21a6e7c7121">

2024-07-25 15:37 UTC, TheGreatAxios approved these changes

2024-07-25 15:37 UTC, merged