config(Node/Supernode): node/subnode -> supernode/node
skalenetwork/docs.skale.space pull request #155
Opened 2024-12-19 15:54 UTC by manuelbarbas

2024-12-26 22:20 UTC, TheGreatAxios requested changes

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/builders/node-operators/skale-nodes.mdx
> +Each SKALE Chain comprises a collective of randomly appointed virtualized nodes that run a containerized SKALE EVM-client daemon (skaled) and SKALE ABBA-based consensus algorithm. Supernodes in the S
Remove virtualized in first sentence

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/builders/node-operators/skale-nodes.mdx
> +Each SKALE Chain comprises a collective of randomly appointed virtualized nodes that run a containerized SKALE EVM-client daemon (skaled) and SKALE ABBA-based consensus algorithm. Supernodes in the S
In the second sentence change virtualized to containerized. 

E.g support multiple chains via containerized nodes

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/builders/node-operators/skale-nodes.mdx
> +Each SKALE Chain comprises a collective of randomly appointed virtualized nodes that run a containerized SKALE EVM-client daemon (skaled) and SKALE ABBA-based consensus algorithm. Supernodes in the S
The last sentence should be node node supernode

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/builders/tools/bridges/index.mdx
> +	/>
Remove extra space

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/ecosystem/validators/compliance-requirements.mdx
> +Failure to follow these requirements will result in a supernodes forfeiting bounty for each month
Sentence on Line 10 -> make supernodes singular e.g supernode

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/ecosystem/validators/compliance-requirements.mdx
> +to ensure your supernodes is operating as intended.
Sentence on Line 13 -> make supernodes singular e.g supernode

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/ecosystem/validators/compliance-requirements.mdx
> +- Don't touch machine firewall (iptables installed by supernode node software automatically sets machine firewall rules), external VPC or networking firewall ensure Ports open on **80, 311, 443,** 30
remove node -> duplicate e.g supernode node change to just supernode

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/ecosystem/validators/validator-cli/overview.mdx
> +On the **SKALE network**, the **validator CLI** (Command Line Interface) is a tool used by validators to interact with the network and manage their validator supernodes. Validators play a crucial rol
capitalize n in SKALE **n**etwork

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/ecosystem/validators/validator-cli/self-recharging-wallets.mdx
> +| alright()      | SKALE Chain Owner    | Performed during SKALE Chain creation when distributed key generation is in-process. Supernodes send receipts of secret key contributions.                |
@DmytroNazarenko Confirming are these functions done at the Supernode or Virtualized Node level?

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/ecosystem/validators/validator-setup.mdx
> +    ### 3.8 Initialize supernode
Capitalize in title e.g Supernode

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/ecosystem/validators/watchdog/apis.mdx
>  == Introduction
Change all == on this page to ## -> Not sure why this didn't get updated during migration

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/ecosystem/validators/watchdog/apis.mdx
Update page from adoc to mdx please

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/ecosystem/validators/watchdog/overview.mdx
> +data on all SKALE supernode docker containers, health checks of sChains and SGX server, Ethereum supernode endpoint
Ethereum node, not supernode

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/learn/about-skale-network.md
> +Decentralized validator organizations run and maintain SKALE Spernodes, providing distributed computing power and storage to the SKALE Network.
Spernodes -> supernodes

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/learn/about-skale-network.md
> +These smart contracts control network functions such as chain creation, validator registration, Supernode selection, node rotation, staking, bounty payment, slashing, and more.
lowercase supernode

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/ecosystem/delegators/overview.mdx
> +who in turn stake the tokens to create SKALE Supernodes. Delegations help
lowercase supernodes

2024-12-26 22:20 UTC, TheGreatAxios commented on src/content/docs/learn/faq.md
> +### What benefits do virtualized nodes and supernodes containerization provide? x
Capitalize in title

2025-01-02 16:16 UTC, manuelbarbas commented on src/content/docs/ecosystem/validators/watchdog/apis.mdx
No sure what you mean here @TheGreatAxios . The file is already .mdx

2025-01-07 19:49 UTC, TheGreatAxios approved these changes

2025-01-07 19:51 UTC, merged