tools code upodate + learn hubs fix
skalenetwork/docs.skale.space pull request #82
Opened 2024-04-19 19:05 UTC by manuelbarbas

2024-05-07 17:06 UTC, TheGreatAxios requested changes

2024-05-07 17:06 UTC, TheGreatAxios commented on src/content/docs/tools/skale/sfuel-distribution/pow_examples/pow_csharp.mdx
I think we should add a note here that says this only works in C# on Mobile/Desktop at this time and not WebGL due to coroutines

2024-05-07 17:06 UTC, TheGreatAxios commented on src/content/docs/tools/skale/sfuel-distribution/pow_examples/pow_dart.mdx
Should we just add skale.dart here to simplify?

2024-05-07 17:06 UTC, TheGreatAxios commented on src/content/docs/tools/skale/sfuel-distribution/pow_examples/pow_javascript.mdx
> +exports.mineGasForTransaction = mineGasForTransaction
add ; at end of line

2024-05-07 17:06 UTC, TheGreatAxios commented on src/styles/overrides.css
> +}
Remove with switch to MathML

2024-05-07 17:06 UTC, TheGreatAxios commented on astro.config.mjs
> +import rehypeMathjax from 'rehype-mathjax';
Remove -> switch to MathML

2024-05-07 17:06 UTC, TheGreatAxios commented on astro.config.mjs
> +	  },
Remove -> switch to MathML

2024-05-07 17:06 UTC, TheGreatAxios commented on src/content/docs/tools/skale/sfuel-distribution/pow_examples/pow_python.mdx
If taken from my repo (remove temporarily as code does not work)

2024-05-08 21:57 UTC, manuelbarbas commented on src/content/docs/tools/skale/sfuel-distribution/pow_examples/pow_dart.mdx
We can my idea was just to have all examples with the same structure. But, for now, I'll add the https://pub.dev/packages/skale there. If you prefer just the repo I'll change

2024-05-08 22:24 UTC, manuelbarbas commented on src/content/docs/tools/skale/sfuel-distribution/contract-distribution.mdx
Do you mean to have a function to give, for example, MINTER_ROLE and distribute sFUEL. Then have other function for mint for MINTER_ROLE access?

2024-05-08 22:25 UTC, manuelbarbas commented on src/content/docs/tools/skale/sfuel-distribution/pow-distribution.mdx
> +| Europa | [0x2B267A3e49b351DEdac892400a530ABb2f899d23](https://elated-tan-skat.explorer.mainnet.skalenodes.com/address/0x2B267A3e49b351DEdac892400a530ABb2f899d23) |[0x366727B410fE55774C8b0B5b5A6E2d7
What does it mean to tab something? (sorry)

2024-05-16 15:21 UTC, TheGreatAxios approved these changes

2024-05-25 00:45 UTC, merged